export default {
    CLOSE_CONTAINER : "close-container",
    ADD_COMMENT : "add-comment",
    COMMENT_FLAG : "comment-flag",
    ELEMENT_BLOCK_LABEL : "element-label",
    DELETE_ELEMENT : "delete-element",
    TCM : "tcm",
    FORWARD_NAVIGATION : "forward-nav-active",
    FORWARD_NAVIGATION_DISABLE : "forward-nav-disable",
    BACKWARD_NAVIGATION : "backward-nav-active",
    BACKWARD_NAVIGATION_DISABLE : "backward-nav-disable",
    EXPAND : "expand",
    SPLIT_SLATE : "split",
    COLOR_PALETTE : "color-palette",
    COLOR_TEXT : "color-text",
    TEXT_ELEMENT : "text-elem",
    IMAGE_ELEMENT : "image-elem",
    AUDIO_ELEMENT : "audio-elem",
    INTERACTIVE_ELEMENT : "interactive-elem-button",
    CONTAINER_ELEMENT : "container-elem-button",    
    WORKED_EXAMPLE_ELEMENT : "worked-exp-elem",
    ASSESSMENT_ELEMENT : "assessment-elem",
    OPENER_ELEMENT : "opener-elem",
    SECTION_BREAK_ELEMENT : "section-break-elem",
    LOCK : "lock-icon",
    METADATA_ANCHOR : "metadata-anchor",
    METADATA_LOList:"metadata-lo-list",
    ELM_CLOSE_WINDOW:"elmCloseWindowIcon",
    ELM_ASSESSMENT_ITEM:"elmAssessmentItem",
    FEEDBACK : "feedback",
    ASSESSMENT_CLOSE_WINDOW:"assessmentCloseWindowIcon",
    CITATION_ELEMENT:'citation-elem',
    STANZA_ELEMENT: "stanza-elem",
    SHOW_HIDE : "show-hide-elem",
    POP_UP : "popup-elem",
    BLOCK_TEXT : "block-text-button",
    TABLE_EDITOR : "table-editor-elem-button",
    MULTI_COLUMN_CONTAINER : "multi-column-group",
    ELM_INTERACTIVE_ICON:"elmInteractiveIcon",
}