export default {
    POETRY : 'poetry',
    POETRY_ELEMENT : 'poetry-elem',
    TEXT : 'text-elem',
    IMAGE : 'image-elem',
    AUDIO : 'audio-elem',
    INTERACTIVE : 'interactive-elem',
    ASSESSMENT: 'assessment-elem',
    CONTAINER: 'container-elem',
    WORKED_EXP: 'worked-exp-elem',
    OPENER: 'opener-elem',
    SECTION_BREAK: 'section-break-elem',
    METADATA_ANCHOR : 'metadata-anchor',
    STANZA_ELEMENT : 'stanza-elem',
    INTERACTIVE_BUTTON : 'interactive-elem-button',
    CITATION :'citation-elem',
    CITATION_GROUP_ELEMENT : 'citations',
    CONTAINER_BUTTON : 'container-elem-button',
    BACK_MATTER : 'Back Matter',
    FRONT_MATTER : 'Front Matter',
    CONTAINER_INTRO : 'container-introduction',
    ELEMENT_ASIDE : 'element-aside'
}